export interface Person {
  table: number;
  num: string;
  tags: string[];
  person: string;
}

export const tables: Person[] = [
  { table: 1, num: "1", tags: ["Mehek", "Ansari"], person: "Mehek Ansari" },
  { table: 0, num: "VIP", tags: ["Moe", "Ansari"], person: "Moe Ansari" },
  { table: 0, num: "VIP", tags: ["Nagma", "Ansari"], person: "Nagma Ansari" },
  { table: 17, num: "17", tags: ["Joji", "Babu"], person: "Joji Babu" },
  { table: 11, num: "11", tags: ["Drew", "Cass"], person: "Drew Cass" },
  {
    table: 11,
    num: "11",
    tags: ["Allison", "Shoemaker"],
    person: "Allison Shoemaker",
  },
  { table: 7, num: "7", tags: ["Mehreen", "Ehsan"], person: "Mehreen Ehsan" },
  { table: 7, num: "7", tags: ["Ehsan", "Akram"], person: "Ehsan Akram" },
  { table: 6, num: "6", tags: ["Maheen", "Khan"], person: "Maheen Khan" },
  { table: 6, num: "6", tags: ["Kamil", "Ali khan"], person: "Kamil Ali khan" },
  { table: 7, num: "7", tags: ["Aarish", "Ehsan"], person: "Aarish Ehsan" },
  { table: 1, num: "1", tags: ["Tasnim", "Alam"], person: "Tasnim Alam" },
  { table: 18, num: "18", tags: ["Afroza", "Alam"], person: "Afroza Alam" },
  { table: 18, num: "18", tags: ["Towhidul", "Alam"], person: "Towhidul Alam" },
  { table: 15, num: "15", tags: ["Brian", "Dennis"], person: "Brian Dennis" },
  {
    table: 17,
    num: "17",
    tags: ["Maria", "Hernandez"],
    person: "Maria Hernandez",
  },
  { table: 9, num: "9", tags: ["Mairaj", "Ahmed"], person: "Mairaj Ahmed" },
  { table: 9, num: "9", tags: ["Elaine", "Ahmed"], person: "Elaine Ahmed" },
  { table: 9, num: "9", tags: ["Aamir", "Ahmed"], person: "Aamir Ahmed" },
  { table: 9, num: "9", tags: ["Rania", "Ahmed"], person: "Rania Ahmed" },
  { table: 9, num: "9", tags: ["Zaara", "Ahmed"], person: "Zaara Ahmed" },
  {
    table: 17,
    num: "17",
    tags: ["Lesbin", "Velasquez"],
    person: "Lesbin Velasquez",
  },
  {
    table: 10,
    num: "10",
    tags: ["Jane", "Cardinale"],
    person: "Jane Cardinale",
  },
  {
    table: 17,
    num: "17",
    tags: ["Gloria", "Frouxides"],
    person: "Gloria Frouxides",
  },
  {
    table: 5,
    num: "5",
    tags: ["Mohammed", "Ansari"],
    person: "Mohammed Ansari",
  },
  { table: 5, num: "5", tags: ["Naheed", "Kauser"], person: "Naheed Kauser" },
  {
    table: 17,
    num: "17",
    tags: ["Vivian", "Spataro"],
    person: "Vivian Spataro",
  },
  { table: 12, num: "12", tags: ["Brenda", "Alfaro"], person: "Brenda Alfaro" },
  {
    table: 12,
    num: "12",
    tags: ["Marilyn", "Alfaro"],
    person: "Marilyn Alfaro",
  },
  { table: 2, num: "2", tags: ["Abdullah", "Malik"], person: "Abdullah Malik" },
  { table: 2, num: "2", tags: ["Naseem", "Malik"], person: "Naseem Malik" },
  { table: 16, num: "16", tags: ["Malik", "Yousaf"], person: "Malik Yousaf" },
  { table: 16, num: "16", tags: ["Mehnaz", "Yousaf"], person: "Mehnaz Yousaf" },
  {
    table: 15,
    num: "15",
    tags: ["Tricia", "LaManna"],
    person: "Tricia LaManna",
  },
  {
    table: 15,
    num: "15",
    tags: ["Nicholas", "LaManna"],
    person: "Nicholas LaManna",
  },
  {
    table: 15,
    num: "15",
    tags: ["Jordyn", "LaManna"],
    person: "Jordyn LaManna",
  },
  { table: 5, num: "5", tags: ["Ilyas", "Subhani"], person: "Ilyas Subhani" },
  { table: 5, num: "5", tags: ["Nazima", "Subhani"], person: "Nazima Subhani" },
  { table: 3, num: "3", tags: ["Nabiha", "Subhani"], person: "Nabiha Subhani" },
  { table: 3, num: "3", tags: ["Yusra", "Subhani"], person: "Yusra Subhani" },
  {
    table: 3,
    num: "3",
    tags: ["Maseera", "Subhani"],
    person: "Maseera Subhani",
  },
  { table: 3, num: "3", tags: ["Uzaire", "Subhani"], person: "Uzaire Subhani" },
  { table: 6, num: "6", tags: ["Tariq", "Siddiqui"], person: "Tariq Siddiqui" },
  { table: 6, num: "6", tags: ["Zuby", "Siddiqui"], person: "Zuby Siddiqui" },
  { table: 10, num: "10", tags: ["Ray", "O’Hara"], person: "Ray O’Hara" },
  {
    table: 10,
    num: "10",
    tags: ["Thressa", "O’Hara"],
    person: "Thressa O’Hara",
  },
  {
    table: 11,
    num: "11",
    tags: ["Luis", "Gutierrez"],
    person: "Luis Gutierrez",
  },
  {
    table: 11,
    num: "11",
    tags: ["Diana", "Gutierrez"],
    person: "Diana Gutierrez",
  },
  { table: 9, num: "9", tags: ["Araj", "Ahmed"], person: "Araj Ahmed" },
  { table: 9, num: "9", tags: ["Imrana", "Ahmed"], person: "Imrana Ahmed" },
  {
    table: 9,
    num: "9",
    tags: ["Kid 1 Araj", "Ahmed"],
    person: "Kid 1 Araj Ahmed",
  },
  {
    table: 9,
    num: "9",
    tags: ["Kid 2 Araj", "Ahmed"],
    person: "Kid 2 Araj Ahmed",
  },
  {
    table: 9,
    num: "9",
    tags: ["Kid 3 Araj", "Ahmed"],
    person: "Kid 3 Araj Ahmed",
  },
  { table: 16, num: "16", tags: ["Asif", "Jamal"], person: "Asif Jamal" },
  { table: 16, num: "16", tags: ["Irrem", "Jamal"], person: "Irrem Jamal" },
  { table: 2, num: "2", tags: ["Sasha", "Jamal"], person: "Sasha Jamal" },
  { table: 2, num: "2", tags: ["Aaleshan", "Jamal"], person: "Aaleshan Jamal" },
  { table: 15, num: "15", tags: ["Larry", "Penn"], person: "Larry Penn" },
  { table: 15, num: "15", tags: ["Kandi", "Penn"], person: "Kandi Penn" },
  { table: 17, num: "17", tags: ["Farzana", "Nifa"], person: "Farzana Nifa" },
  {
    table: 17,
    num: "17",
    tags: ["Makhjoom", "Ferdous"],
    person: "Makhjoom Ferdous",
  },
  {
    table: 6,
    num: "6",
    tags: ["Masihuddin", "Syed"],
    person: "Masihuddin Syed",
  },
  { table: 6, num: "6", tags: ["Nasreen", "Syed"], person: "Nasreen Syed" },
  {
    table: 18,
    num: "18",
    tags: ["Jazmid", "Martínez"],
    person: "Jazmid Martínez",
  },
  {
    table: 18,
    num: "18",
    tags: ["Danny", "Martínez"],
    person: "Danny Martínez",
  },
  { table: 4, num: "4", tags: ["Masroor", "Syed"], person: "Masroor Syed" },
  { table: 4, num: "4", tags: ["Farah", "Syed"], person: "Farah Syed" },
  { table: 2, num: "2", tags: ["Sheryar", "Syed"], person: "Sheryar Syed" },
  { table: 2, num: "2", tags: ["Shiraz", "Syed"], person: "Shiraz Syed" },
  {
    table: 10,
    num: "10",
    tags: ["Dean", "Cardinale"],
    person: "Dean Cardinale",
  },
  {
    table: 10,
    num: "10",
    tags: ["Diane", "Cardinale"],
    person: "Diane Cardinale",
  },
  {
    table: 10,
    num: "10",
    tags: ["Aidan", "Cardinale"],
    person: "Aidan Cardinale",
  },
  { table: 7, num: "7", tags: ["Nomaan", "Ansari"], person: "Nomaan Ansari" },
  { table: 3, num: "3", tags: ["Siraj", "Ansari"], person: "Siraj Ansari" },
  { table: 7, num: "7", tags: ["Adalina", "Ansari"], person: "Adalina Ansari" },
  {
    table: 5,
    num: "5",
    tags: ["Mohammed", "Ansari"],
    person: "Mohammed Ansari",
  },
  { table: 10, num: "10", tags: ["Brenda", "Rojas"], person: "Brenda Rojas" },
  { table: 10, num: "10", tags: ["Teddy", "Rojas"], person: "Teddy Rojas" },
  { table: 15, num: "15", tags: ["Dan", "Martinez"], person: "Dan Martinez" },
  {
    table: 15,
    num: "15",
    tags: ["Stephen", "Gorgone"],
    person: "Stephen Gorgone",
  },
  {
    table: 1,
    num: "1",
    tags: ["Hector N", "Colon III"],
    person: "Hector N Colon III",
  },
  { table: 0, num: "VIP", tags: ["Naheed", "Kareem"], person: "Naheed Kareem" },
  { table: 5, num: "5", tags: ["Kamal", "Kareem"], person: "Kamal Kareem" },
  { table: 5, num: "5", tags: ["Juveria", "Kareem"], person: "Juveria Kareem" },
  { table: 5, num: "5", tags: ["Omar", "Kareem"], person: "Omar Kareem" },
  { table: 2, num: "2", tags: ["Sumaa", "Saleem"], person: "Sumaa Saleem" },
  { table: 6, num: "6", tags: ["Asma", "Saleem"], person: "Asma Saleem" },
  { table: 6, num: "6", tags: ["Zaffar", "Saleem"], person: "Zaffar Saleem" },
  { table: 1, num: "1", tags: ["Lara", "Mallon"], person: "Lara Mallon" },
  { table: 8, num: "8", tags: ["Marlene", "Oliva"], person: "Marlene Oliva" },
  { table: 8, num: "8", tags: ["Aatif", "Siddiqui"], person: "Aatif Siddiqui" },
  {
    table: 8,
    num: "8",
    tags: ["Dayanara", "Siddiqui"],
    person: "Dayanara Siddiqui",
  },
  { table: 1, num: "1", tags: ["Lauren", "Kittle"], person: "Lauren Kittle" },
  {
    table: 15,
    num: "15",
    tags: ["Lisa", "Bonsignore"],
    person: "Lisa Bonsignore",
  },
  { table: 14, num: "14", tags: ["Ron", "Kramer"], person: "Ron Kramer" },
  { table: 13, num: "13", tags: ["Kevin", "Sookoo"], person: "Kevin Sookoo" },
  { table: 13, num: "13", tags: ["Mala", "Sookoo"], person: "Mala Sookoo" },
  { table: 13, num: "13", tags: ["Laila", "Sookoo"], person: "Laila Sookoo" },
  { table: 13, num: "13", tags: ["Lucas", "Sookoo"], person: "Lucas Sookoo" },
  { table: 13, num: "13", tags: ["Naveen", "Bhanot"], person: "Naveen Bhanot" },
  { table: 13, num: "13", tags: ["Neenu", "Bhanot"], person: "Neenu Bhanot" },
  { table: 3, num: "3", tags: ["Shubham", "Bhanot"], person: "Shubham Bhanot" },
  { table: 3, num: "3", tags: ["Shloak", "Bhanot"], person: "Shloak Bhanot" },
  {
    table: 18,
    num: "18",
    tags: ["Tanziha", "Rahman"],
    person: "Tanziha Rahman",
  },
  { table: 18, num: "18", tags: ["Sakeel", "Ahmed"], person: "Sakeel Ahmed" },
  {
    table: 1,
    num: "1",
    tags: ["Jamey", "Almendarez Barahona"],
    person: "Jamey Almendarez Barahona",
  },
  { table: 9, num: "9", tags: ["Younus", "Ahmed"], person: "Younus Ahmed" },
  { table: 9, num: "9", tags: ["Taruj", "Ahmed"], person: "Taruj Ahmed" },
  { table: 9, num: "9", tags: ["Shahana", "Ahmed"], person: "Shahana Ahmed" },
  { table: 3, num: "3", tags: ["Shaan", "Ahmed"], person: "Shaan Ahmed" },
  { table: 3, num: "3", tags: ["Nayab", "Ahmed"], person: "Nayab Ahmed" },
  { table: 7, num: "7", tags: ["Rizwaan", "Ansari"], person: "Rizwaan Ansari" },
  { table: 3, num: "3", tags: ["Ali", "Ansari"], person: "Ali Ansari" },
  { table: 3, num: "3", tags: ["Nazir", "Ansari"], person: "Nazir Ansari" },
  { table: 5, num: "5", tags: ["Saleha", "Ahmed"], person: "Saleha Ahmed" },
  { table: 5, num: "5", tags: ["Faiz", "Kareem"], person: "Faiz Kareem" },
  { table: 3, num: "3", tags: ["Sabrina", "Kareem"], person: "Sabrina Kareem" },
  { table: 18, num: "18", tags: ["Mr", "Kaur"], person: "Mr Kaur" },
  { table: 18, num: "18", tags: ["Mrs", "Kaur"], person: "Mrs Kaur" },
  { table: 17, num: "17", tags: ["Tom", "Connelly"], person: "Tom Connelly" },
  {
    table: 17,
    num: "17",
    tags: ["Angela", "Connelly"],
    person: "Angela Connelly",
  },
  { table: 15, num: "15", tags: ["Jim", "Flynn"], person: "Jim Flynn" },
  { table: 18, num: "18", tags: ["Sharifa", "Jahan"], person: "Sharifa Jahan" },
  { table: 18, num: "18", tags: ["Mohammed", "Ali"], person: "Mohammed Ali" },
  { table: 0, num: "VIP", tags: ["Neal", "Wadhwa"], person: "Neal Wadhwa" },
  { table: 1, num: "1", tags: ["Diego", "Cardenas"], person: "Diego Cardenas" },
  { table: 4, num: "4", tags: ["Huma", "Rasheed"], person: "Huma Rasheed" },
  { table: 4, num: "4", tags: ["Fawad", "Maqbool"], person: "Fawad Maqbool" },
  {
    table: 2,
    num: "2",
    tags: ["Shehzad", "Maqbool"],
    person: "Shehzad Maqbool",
  },
  { table: 16, num: "16", tags: ["Rabia", "Iqbal"], person: "Rabia Iqbal" },
  { table: 16, num: "16", tags: ["Asim", "Rehman"], person: "Asim Rehman" },
  { table: 2, num: "2", tags: ["Sarah", "Khan"], person: "Sarah Khan" },
  { table: 2, num: "2", tags: ["Shazaib", "Khan"], person: "Shazaib Khan" },
  {
    table: 11,
    num: "11",
    tags: ["Mr.Daniel", "Riveira"],
    person: "Mr.Daniel Riveira",
  },
  {
    table: 11,
    num: "11",
    tags: ["Mrs.Daniel", "Riveira"],
    person: "Mrs.Daniel Riveira",
  },
  { table: 12, num: "12", tags: ["Maritza", "Munoz"], person: "Maritza Munoz" },
  { table: 12, num: "12", tags: ["Gabriella", "Ch."], person: "Gabriella Ch." },
  {
    table: 14,
    num: "14",
    tags: ["Carlos", "Collazos"],
    person: "Carlos Collazos",
  },
  {
    table: 14,
    num: "14",
    tags: ["Ceyanira", "Collazos"],
    person: "Ceyanira Collazos",
  },
  {
    table: 1,
    num: "1",
    tags: ["Addison", "Alexander"],
    person: "Addison Alexander",
  },
  {
    table: 1,
    num: "1",
    tags: ["Tiffani", "Guichardo"],
    person: "Tiffani Guichardo",
  },
  { table: 12, num: "12", tags: ["Deisy", "Mendez"], person: "Deisy Mendez" },
  { table: 12, num: "12", tags: ["Abner", "Escobar"], person: "Abner Escobar" },
  {
    table: 12,
    num: "12",
    tags: ["Natania", "Escobar"],
    person: "Natania Escobar",
  },
  { table: 12, num: "12", tags: ["Yosef", "Escobar"], person: "Yosef Escobar" },
  {
    table: 0,
    num: "VIP",
    tags: ["Dr.Nand", "Wadhwa"],
    person: "Dr.Nand Wadhwa",
  },
  { table: 14, num: "14", tags: ["Mary", "Vera"], person: "Mary Vera" },
  { table: 14, num: "14", tags: ["Rafael", "Baez"], person: "Rafael Baez" },
  { table: 14, num: "14", tags: ["Yamalay", "Baez"], person: "Yamalay Baez" },
  { table: 12, num: "12", tags: ["Iriana", "Jacobo"], person: "Iriana Jacobo" },
  { table: 12, num: "12", tags: ["Aiden", "Morel"], person: "Aiden Morel" },
  {
    table: 11,
    num: "11",
    tags: ["Sudip", "Mukherjee"],
    person: "Sudip Mukherjee",
  },
  {
    table: 11,
    num: "11",
    tags: ["Tina", "Mukherjee"],
    person: "Tina Mukherjee",
  },
  {
    table: 11,
    num: "11",
    tags: ["Aryan", "Mukherjee"],
    person: "Aryan Mukherjee",
  },
  {
    table: 11,
    num: "11",
    tags: ["Simone", "Mukherjee"],
    person: "Simone Mukherjee",
  },
  {
    table: 13,
    num: "13",
    tags: ["Chris", "Arredondo"],
    person: "Chris Arredondo",
  },
  {
    table: 13,
    num: "13",
    tags: ["Mariana", "Arredondo"],
    person: "Mariana Arredondo",
  },
  {
    table: 13,
    num: "13",
    tags: ["Andrea", "Arredondo"],
    person: "Andrea Arredondo",
  },
  { table: 4, num: "4", tags: ["Assad", "Siddiqui"], person: "Assad Siddiqui" },
  {
    table: 4,
    num: "4",
    tags: ["Sakina", "Siddiqui"],
    person: "Sakina Siddiqui",
  },
  { table: 4, num: "4", tags: ["Saif", "Siddiqui"], person: "Saif Siddiqui" },
  { table: 10, num: "10", tags: ["Jeff", "Modell"], person: "Jeff Modell" },
  { table: 10, num: "10", tags: ["Meagan", "Modell"], person: "Meagan Modell" },
  {
    table: 12,
    num: "12",
    tags: ["Brenda", "Fuentes"],
    person: "Brenda Fuentes",
  },
  { table: 1, num: "1", tags: ["Abbie", "Chen"], person: "Abbie Chen" },
  { table: 1, num: "1", tags: ["Afia", "Nasim"], person: "Afia Nasim" },
  { table: 15, num: "15", tags: ["Snovia", "Ansari"], person: "Snovia Ansari" },
  { table: 4, num: "4", tags: ["Tahir", "Nazir"], person: "Tahir Nazir" },
  { table: 4, num: "4", tags: ["Samina", "Nazir"], person: "Samina Nazir" },
  { table: 13, num: "13", tags: ["Ali", "Nazir"], person: "Ali Nazir" },
  { table: 13, num: "13", tags: ["Mrs.Ali", "Nazir"], person: "Mrs.Ali Nazir" },
  {
    table: 8,
    num: "8",
    tags: ["Nadeem", "Siddiqui"],
    person: "Nadeem Siddiqui",
  },
  { table: 8, num: "8", tags: ["Sana", "Siddiqui"], person: "Sana Siddiqui" },
  { table: 8, num: "8", tags: ["Zain", "Siddiqui"], person: "Zain Siddiqui" },
  {
    table: 8,
    num: "8",
    tags: ["Kid #2 Nadeem", "Siddiqui"],
    person: "Kid #2 Nadeem Siddiqui",
  },
  {
    table: 6,
    num: "6",
    tags: ["Dr.Shaukat I.", "Siddiki"],
    person: "Dr.Shaukat I. Siddiki",
  },
  {
    table: 6,
    num: "6",
    tags: ["Mrs.Marium", "Shaukat"],
    person: "Mrs.Marium Shaukat",
  },
  { table: 8, num: "8", tags: ["Oran", "Day"], person: "Oran Day" },
  { table: 8, num: "8", tags: ["Sabah", "Day"], person: "Sabah Day" },
  { table: 8, num: "8", tags: ["Kid #1", "Day"], person: "Kid #1 Day" },
  { table: 8, num: "8", tags: ["Kid #2", "Day"], person: "Kid #2 Day" },
  { table: 1, num: "1", tags: ["Kayla", "Huynh"], person: "Kayla Huynh" },
  { table: 1, num: "1", tags: ["Leann", "Huynh"], person: "Leann Huynh" },
  { table: 1, num: "1", tags: ["Daniela", "Aleman"], person: "Daniela Aleman" },
  {
    table: 1,
    num: "1",
    tags: ["Christopher", "Nostramo"],
    person: "Christopher Nostramo",
  },
  { table: 1, num: "1", tags: ["Mirac", "sevencan"], person: "Mirac sevencan" },
  { table: 0, num: "VIP", tags: ["Khalida", "Khala"], person: "Khalida Khala" },
  { table: 7, num: "7", tags: ["Iqbal", "Syed"], person: "Iqbal Syed" },
  {
    table: 7,
    num: "7",
    tags: ["Mansoor", "Maqbool"],
    person: "Mansoor Maqbool",
  },
  {
    table: 0,
    num: "VIP",
    tags: ["Mohammadi", "Maqbool"],
    person: "Mohammadi Maqbool",
  },
  { table: 2, num: "2", tags: ["Faraz", "Maqbool"], person: "Faraz Maqbool" },
  { table: 6, num: "6", tags: ["Akbar", "Siddiqui"], person: "Akbar Siddiqui" },
  { table: 6, num: "6", tags: ["Asima", "Siddiqui"], person: "Asima Siddiqui" },
  { table: 15, num: "15", tags: ["Priya", "Gooty"], person: "Priya Gooty" },
  { table: 1, num: "1", tags: ["Ashley", "Zavala"], person: "Ashley Zavala" },
  { table: 4, num: "4", tags: ["Shoaib", "Nazir"], person: "Shoaib Nazir" },
  { table: 4, num: "4", tags: ["Kauser", "Nazir"], person: "Kauser Nazir" },
  { table: 7, num: "7", tags: ["Zulfi", "Nazir"], person: "Zulfi Nazir" },
  { table: 5, num: "5", tags: ["Lubna", "Quadri"], person: "Lubna Quadri" },
  { table: 4, num: "4", tags: ["Faryal", "Qurashi"], person: "Faryal Qurashi" },
  { table: 8, num: "8", tags: ["Aatif", "MIL"], person: "Aatif MIL" },
  { table: 7, num: "7", tags: ["Muhamad", "Akram"], person: "Muhamad Akram" },
  { table: 7, num: "7", tags: ["Shabana", "Akram"], person: "Shabana Akram" },
];

export function findNameInTable(search: string) {
  return tables.filter((person) => {
    return person.tags.some((tag) => tag.toLowerCase().includes(search));
  });
}
